// for slack purposes, define a variable called COLOR_MAP
def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]

pipeline {
    agent any
    tools {
        maven "maven3"
        jdk "jdk8"
    }
    
    environment {
        // add ecs cluster
        clusterECS = 'ProdCluster'
        // add ecs service
        serviceECS = 'AppProdService'
    }

    stages {

        stage('Deploy to ECS production'){
            steps{
                // set id credential you set in jenkins for aws login
                withAWS(credentials: 'aws', region: 'us-east-1'){
                    sh 'aws ecs update-service --cluster ${clusterECS} --service ${serviceECS} --force-new-deployment'
                }
            }
        }

    }
    // add slack for notification
    post {
        always {
            echo 'Slack Notifications.'
            // set your channel name
            slackSend channel: '#cicd',
                /*
                    For more information about Jenkins global variable "currentBuild" please visit the following:
                    https://kb.novaordis.com/index.php/Jenkins_currentBuild

                    COLOR_MAP Variable is defined previously in line 2
                */
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}